#!/bin/sh
BASEIRI="https://go.KIBI.family/"
CORPUS="$1"
PREFIX="Corpora/"
NOTESDIR=":notes"
SHORTPREFIX="$(echo "$CORPUS" | tr "[:upper:]/" "[:lower:]:"):"
RDF="index.rdf"
generateIndex(){
	SHORTPATH="$(echo "$1" | tr "/" ":")" && [[ "$(basename "$1")" == "$NOTESDIR" ]] && SHORTPATH="$(echo "$(dirname "$1")" | tr "/" ":")"
	if [ -f "$1/.nobranch" ] ; then
		:
	else
		echo "<!dOcTyPe HtMl><HTML Lang=en><TITLE>Redirect to description</TITLE><BASE HRef='$BASEIRI$PREFIX$CORPUS/'><LINK Rel=alternate HRef='$RDF' Type=application/rdf+xml><META Http-Equiv=refresh Content='0; $BASEIRI$PREFIX$CORPUS/#$SHORTPREFIX$SHORTPATH'><P><A HRef='#$SHORTPREFIX$SHORTPATH'>View this directory’s description in the BNS corpus.</A>" > "$1/index.html"
		if [ "$(ls -A $1)" ] ; then
			for D in "$1/"* ; do
				if [ -L "$D" ] ; then
					:
				elif [ -d "$D" ] ; then
					generateIndex "$D"
				fi
			done
		fi
	fi
}
if [ "$CORPUS" ] ; then
	cd "$PREFIX$CORPUS"
	if [ "$(ls -A .)" ] ; then
		for D in * ; do
			if [ -L "$D" ] ; then
				:
			elif [ -d "$D" ] ; then
				generateIndex "$D"
			fi
		done
	fi
else echo 'Please specify a corpus!'
fi
